# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'

    # La session est activée avec les valeurs par défaut :
    # cookie_secure = auto, cookie_samesite = lax
    session: true

    # Trusted proxies (Ngrok, reverse proxies)
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers:
        - x-forwarded-for
        - x-forwarded-proto
        - x-forwarded-port
        - x-forwarded-host

    #esi: true
    #fragments: true

# Configuration spécifique aux tests
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
